export const REPOSITORY_TOKENS = {
    USER_REPOSITORY: 'USER_REPOSITORY_TOKEN',
    AUTH_REPOSITORY: 'AUTH_REPOSITORY_TOKEN',
};

export const SERVICE_TOKENS = {
    CACHE_SERVICE: 'CACHE_SERVICE_TOKEN',
    LOGGER_SERVICE: 'LOGGER_SERVICE_TOKEN',
};
